openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    ErrorResponse:
      type: object
      description: A response that denotes that an error has occurred.
      properties:
        name:
          type: "string"
          description: A brief descriptive name for the error.
          pattern: "[a-z0-9\\-]{8,}"
        message:
          type: "string"
          description: Human-readable detail about the error.
          minLength: 10
          maxLength: 100
        details:
          type: "object"
          description: An object with error details.
      required: ["name", "message"]
      example:
        {
          "name": "Invalid JSON",
          "message": "The provided JSON data was malformed."
        }
